---
output:
  pdf_document: default
  word_document: default
  html_document: default
---
# KSBound: Kernel Stick-Breaking Prior Distribution for Spatial Boundary Detection

## Statistical Model
$$Y_i|\text{E}_i, \lambda_i \stackrel{\text{ind}}{\sim} \text{Poisson}\left(\text{E}_i\lambda_i\right),\ \ln\left(\lambda_i\right) = \textbf{x}_i^{\text{T}} \boldsymbol{\beta} + \eta_i,\ i=1,...,n;$$

$$\eta_i|\boldsymbol{p}_i, \boldsymbol{\theta}\stackrel{\text{ind}}{\sim}G_i,\ G_i\left(.\right)\stackrel{d}{=}\sum_{j=1}^{\infty} p_{ij}\delta_{\theta_j}\left(.\right),\ i=1,...,n;$$

$$p_{i1} = w_{i1}V_1,\ p_{ij} = w_{ij}V_j\prod_{k=1}^{j-1}\left(1 - w_{ik}V_k\right) \text{ for } j \geq 2;$$

* $V_k|\alpha \stackrel{\text{iid}}{\sim}\text{Beta}\left(1, \alpha\right)$; 

* $\theta_j|\sigma^2_{\theta} \stackrel{\text{iid}}{\sim}\text{N}\left(0, \sigma^2_{\theta}\right);$

\begin{align*}\begin{split} &w_{ij} = 1\left(R_i \in \partial_{R_{\psi_j}}\right),\  \partial_{R_{\psi_j}}=\left\{R_{\psi_j}\right\} \cup \left\{R_k: R_k \text{ and } R_{\psi_j} \text{ are neighbors}\right\}, \\ &\psi_j \stackrel{\text{iid}}{\sim}\text{Discrete Uniform}\left\{1, n\right\}. \end{split}
\end{align*}


## Prior Information
$\beta_j \stackrel{\text{iid}}{\sim}\text{N}\left(0, \sigma^2_{\beta}\right),\ j=1,...,p;$

* $p$: Length of $\textbf{x}_i$ vector (same for all $i$);

* Default setting: $\sigma^2_{\beta} = 10,000.$

$\sigma^2_{\theta} \sim \text{Inverse Gamma}\left(a_{\sigma^2_{\theta}}, b_{\sigma^2_{\theta}}\right);$

* Default setting: $a_{\sigma^2_{\theta}} = 0.01$, $b_{\sigma^2_{\theta}} = 0.01.$

$\alpha \sim \text{Gamma}\left(a_{\alpha}, b_{\alpha}\right);$

* Default setting: $a_{\alpha} = 0.01$, $b_{\alpha} = 0.01.$

## Default Initial Values
* $\beta_j = 0$ for all $j$;

* $\theta_j = 0$ for all $j$;

* $\sigma^2_{\theta} = 1.00$;

* $\alpha = 1.00$;

* $V_j = 0.99$ for all $j$;

* $\psi_j = j$ for all $j$.

## Alternate Likelihood: Binomial
$Y_i|\boldsymbol{\beta}, \eta_i, r \stackrel{\text{ind}}{\sim} \text{Binomial}\left\{c_i, p_i\left(\boldsymbol{\beta}, \eta_i\right)\right\},\ i=1,...,n;$

$\text{ln}\left\{\frac{p_i\left(\boldsymbol{\beta}, \eta_i\right)}{1 - p_i\left(\boldsymbol{\beta}, \eta_i\right)}\right\} = \textbf{x}_i^{\text{T}} \boldsymbol{\beta} + \eta_i.$

## Alternate Likelihood: Gaussian
$Y_i|\boldsymbol{\beta}, \eta_i, \sigma^2_{\epsilon} \stackrel{\text{ind}}{\sim} \text{Normal}\left(\textbf{x}_i^{\text{T}} \boldsymbol{\beta} + \eta_i, \sigma^2_{\epsilon}\right),\ i=1,...,n.$

* $\sigma^2_{\epsilon} \sim \text{Inverse Gamma}\left(a_{\sigma^2_{\epsilon}}, b_{\sigma^2_{\epsilon}}\right);$ 

* Default setting: $a_{\sigma^2_{\epsilon}} = 0.01$, $b_{\sigma^2_{\epsilon}} = 0.01$; 

* Default initial value: $\sigma^2_{\epsilon} = \text{variance}\left(\boldsymbol{Y}\right)$.

## Alternate Likelihood: Negative Binomial
$Y_i|\boldsymbol{\beta}, \eta_i, r \stackrel{\text{ind}}{\sim} \text{Negative Binomial}\left\{r, \lambda_i\left(\boldsymbol{\beta}, \eta_i\right)\right\},\ i=1,...,n;$

$\text{ln}\left\{\frac{\lambda_i\left(\boldsymbol{\beta}, \eta_i\right)}{1 - \lambda_i\left(\boldsymbol{\beta}, \eta_i\right)}\right\} = \ln\left(\text{E}_i\right) + \textbf{x}_i^{\text{T}} \boldsymbol{\beta} + \eta_i.$

* $r \sim \text{Discrete Uniform}\left[a_r, b_r\right];$ 

* Default setting: $a_r = 1$, $b_r = 100$; 

* Default initial value: $r = b_r$.

## Likelihood Indicator
* likelihood_indicator $= 0$: Poisson; 

* likelihood_indicator $= 1$: Binomial; 

* likelihood_indicator $= 2$: Gaussian;

* likelihood_indicator $= 3$: Negative binomial.

