# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

KSBound <- function(mcmc_samples, m_max, spatial_neighbors, y, offset, x, mhvar_beta, mhvar_theta, beta_mu_prior = NULL, beta_sd_prior = NULL, sigma2_theta_a_prior = NULL, sigma2_theta_b_prior = NULL, alpha_a_prior = NULL, alpha_b_prior = NULL, beta_init = NULL, theta_init = NULL, sigma2_theta_init = NULL, g_init = NULL, v_init = NULL, alpha_init = NULL, psi_init = NULL, alpha_fix = NULL, keep_all_ind = NULL) {
    .Call(`_KSBound_KSBound`, mcmc_samples, m_max, spatial_neighbors, y, offset, x, mhvar_beta, mhvar_theta, beta_mu_prior, beta_sd_prior, sigma2_theta_a_prior, sigma2_theta_b_prior, alpha_a_prior, alpha_b_prior, beta_init, theta_init, sigma2_theta_init, g_init, v_init, alpha_init, psi_init, alpha_fix, keep_all_ind)
}

alpha_update <- function(v, alpha_a, alpha_b) {
    .Call(`_KSBound_alpha_update`, v, alpha_a, alpha_b)
}

beta_update <- function(y, offset, x, beta_old, theta_old, g_old, beta_mu, beta_sd, mhvar_beta, acctot_beta) {
    .Call(`_KSBound_beta_update`, y, offset, x, beta_old, theta_old, g_old, beta_mu, beta_sd, mhvar_beta, acctot_beta)
}

g_update <- function(y, offset, x, beta, theta, c, u, p) {
    .Call(`_KSBound_g_update`, y, offset, x, beta, theta, c, u, p)
}

neg_two_loglike_update <- function(y, offset, x, beta, theta, g) {
    .Call(`_KSBound_neg_two_loglike_update`, y, offset, x, beta, theta, g)
}

sigma2_theta_update <- function(theta, sigma2_theta_a, sigma2_theta_b) {
    .Call(`_KSBound_sigma2_theta_update`, theta, sigma2_theta_a, sigma2_theta_b)
}

theta_update <- function(y, offset, x, beta, theta_old, sigma2_theta_old, g_old, mhvar_theta, acctot_theta) {
    .Call(`_KSBound_theta_update`, y, offset, x, beta, theta_old, sigma2_theta_old, g_old, mhvar_theta, acctot_theta)
}

u_p_c_update <- function(spatial_neighbors, v, psi, g) {
    .Call(`_KSBound_u_p_c_update`, spatial_neighbors, v, psi, g)
}

v_psi_update <- function(m_max, spatial_neighbors, y, g, alpha_old) {
    .Call(`_KSBound_v_psi_update`, m_max, spatial_neighbors, y, g, alpha_old)
}

