# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

alpha_update <- function(v, alpha_a, alpha_b) {
    .Call(`_KSBound_alpha_update`, v, alpha_a, alpha_b)
}

beta_update <- function(y, offset, x, beta_old, theta_old, g_old, beta_mu, beta_sd, mhvar_beta, acctot_beta) {
    .Call(`_KSBound_beta_update`, y, offset, x, beta_old, theta_old, g_old, beta_mu, beta_sd, mhvar_beta, acctot_beta)
}

g_update <- function(y, offset, x, beta, theta, c, u, p) {
    .Call(`_KSBound_g_update`, y, offset, x, beta, theta, c, u, p)
}

KSBound <- function(mcmc_samples, m_max, spatial_neighbors, y, offset, x, beta_mu, beta_sd, sigma2_theta_a, sigma2_theta_b, alpha_a, alpha_b, mhvar_beta, mhvar_theta, beta_init, theta_init, sigma2_theta_init, g_init, v_init, alpha_init, psi_init, u_init, c_init, p_init, neg_two_loglike_init) {
    .Call(`_KSBound_KSBound`, mcmc_samples, m_max, spatial_neighbors, y, offset, x, beta_mu, beta_sd, sigma2_theta_a, sigma2_theta_b, alpha_a, alpha_b, mhvar_beta, mhvar_theta, beta_init, theta_init, sigma2_theta_init, g_init, v_init, alpha_init, psi_init, u_init, c_init, p_init, neg_two_loglike_init)
}

neg_two_loglike_update <- function(y, offset, x, beta, theta, g) {
    .Call(`_KSBound_neg_two_loglike_update`, y, offset, x, beta, theta, g)
}

sigma2_theta_update <- function(theta, sigma2_theta_a, sigma2_theta_b) {
    .Call(`_KSBound_sigma2_theta_update`, theta, sigma2_theta_a, sigma2_theta_b)
}

theta_update <- function(y, offset, x, beta, theta_old, sigma2_theta_old, g_old, mhvar_theta, acctot_theta) {
    .Call(`_KSBound_theta_update`, y, offset, x, beta, theta_old, sigma2_theta_old, g_old, mhvar_theta, acctot_theta)
}

u_p_c_update <- function(spatial_neighbors, v, psi, g) {
    .Call(`_KSBound_u_p_c_update`, spatial_neighbors, v, psi, g)
}

v_psi_update <- function(m_max, spatial_neighbors, y, g, alpha_old) {
    .Call(`_KSBound_v_psi_update`, m_max, spatial_neighbors, y, g, alpha_old)
}

